# Generated from the provider's pinned SQLite source fixture.
# Edit the generator inputs, then regenerate; do not edit this file by hand.
# SPDX-License-Identifier: BSD-3-Clause

entity "actor" {
  key = ["actor_id"]

  property "actor_id" {
    type = "int"
  }

  property "first_name" {
    required = true
    type = "string"
  }

  property "last_name" {
    required = true
    type = "string"
  }

  property "last_update" {
    required = true
    type = "string"
  }
}

entity "address" {
  key = ["address_id"]

  property "address_id" {
    type = "int"
  }

  property "address" {
    required = true
    type = "string"
  }

  property "address2" {
    type = "string"
  }

  property "district" {
    required = true
    type = "string"
  }

  property "city_id" {
    required = true
    entity = "city"
  }

  property "postal_code" {
    type = "string"
  }

  property "phone" {
    required = true
    type = "string"
  }

  property "location" {
    required = true
    type = "document"
  }

  property "last_update" {
    required = true
    type = "string"
  }
}

entity "category" {
  key = ["category_id"]

  property "category_id" {
    type = "int"
  }

  property "name" {
    required = true
    type = "string"
  }

  property "last_update" {
    required = true
    type = "string"
  }
}

entity "city" {
  key = ["city_id"]

  property "city_id" {
    type = "int"
  }

  property "city" {
    required = true
    type = "string"
  }

  property "country_id" {
    required = true
    entity = "country"
  }

  property "last_update" {
    required = true
    type = "string"
  }
}

entity "country" {
  key = ["country_id"]

  property "country_id" {
    type = "int"
  }

  property "country" {
    required = true
    type = "string"
  }

  property "last_update" {
    required = true
    type = "string"
  }
}

entity "customer" {
  key = ["customer_id"]

  property "customer_id" {
    type = "int"
  }

  property "store_id" {
    required = true
    entity = "store"
  }

  property "first_name" {
    required = true
    type = "string"
  }

  property "last_name" {
    required = true
    type = "string"
  }

  property "email" {
    type = "string"
  }

  property "address_id" {
    required = true
    entity = "address"
  }

  property "active" {
    required = true
    type = "int"
  }

  property "create_date" {
    required = true
    type = "string"
  }

  property "last_update" {
    type = "string"
  }
}

entity "film" {
  key = ["film_id"]

  property "film_id" {
    type = "int"
  }

  property "title" {
    required = true
    type = "string"
  }

  property "description" {
    type = "string"
  }

  property "release_year" {
    type = "string"
  }

  property "language_id" {
    required = true
    entity = "language"
  }

  property "original_language_id" {
    entity = "language"
  }

  property "rental_duration" {
    required = true
    type = "int"
  }

  property "rental_rate" {
    required = true
    type = "decimal"
  }

  property "length" {
    type = "int"
  }

  property "replacement_cost" {
    required = true
    type = "decimal"
  }

  property "rating" {
    type = "string"
  }

  property "special_features" {
    type = "string"
  }

  property "last_update" {
    required = true
    type = "string"
  }
}

entity "film_actor" {
  key = ["actor_id","film_id"]

  property "actor_id" {
    required = true
    entity = "actor"
  }

  property "film_id" {
    required = true
    entity = "film"
  }

  property "last_update" {
    required = true
    type = "string"
  }
}

entity "film_category" {
  key = ["film_id","category_id"]

  property "film_id" {
    required = true
    entity = "film"
  }

  property "category_id" {
    required = true
    entity = "category"
  }

  property "last_update" {
    required = true
    type = "string"
  }
}

entity "film_text" {
  key = ["film_id"]

  property "film_id" {
    required = true
    type = "int"
  }

  property "title" {
    required = true
    type = "string"
  }

  property "description" {
    type = "string"
  }
}

entity "inventory" {
  key = ["inventory_id"]

  property "inventory_id" {
    type = "int"
  }

  property "film_id" {
    required = true
    entity = "film"
  }

  property "store_id" {
    required = true
    entity = "store"
  }

  property "last_update" {
    required = true
    type = "string"
  }
}

entity "language" {
  key = ["language_id"]

  property "language_id" {
    type = "int"
  }

  property "name" {
    required = true
    type = "string"
  }

  property "last_update" {
    required = true
    type = "string"
  }
}

entity "payment" {
  key = ["payment_id"]

  property "payment_id" {
    type = "int"
  }

  property "customer_id" {
    required = true
    entity = "customer"
  }

  property "staff_id" {
    required = true
    entity = "staff"
  }

  property "rental_id" {
    entity = "rental"
  }

  property "amount" {
    required = true
    type = "decimal"
  }

  property "payment_date" {
    required = true
    type = "string"
  }

  property "last_update" {
    type = "string"
  }
}

entity "rental" {
  key = ["rental_id"]

  property "rental_id" {
    type = "int"
  }

  property "rental_date" {
    required = true
    type = "string"
  }

  property "inventory_id" {
    required = true
    entity = "inventory"
  }

  property "customer_id" {
    required = true
    entity = "customer"
  }

  property "return_date" {
    type = "string"
  }

  property "staff_id" {
    required = true
    entity = "staff"
  }

  property "last_update" {
    required = true
    type = "string"
  }
}

entity "staff" {
  key = ["staff_id"]

  property "staff_id" {
    type = "int"
  }

  property "first_name" {
    required = true
    type = "string"
  }

  property "last_name" {
    required = true
    type = "string"
  }

  property "address_id" {
    required = true
    entity = "address"
  }

  property "picture" {
    type = "document"
  }

  property "email" {
    type = "string"
  }

  property "store_id" {
    required = true
    entity = "store"
  }

  property "active" {
    required = true
    type = "int"
  }

  property "username" {
    required = true
    type = "string"
  }

  property "password" {
    type = "string"
  }

  property "last_update" {
    required = true
    type = "string"
  }
}

entity "store" {
  key = ["store_id"]

  property "store_id" {
    type = "int"
  }

  property "manager_staff_id" {
    required = true
    entity = "staff"
  }

  property "address_id" {
    required = true
    entity = "address"
  }

  property "last_update" {
    required = true
    type = "string"
  }
}
